name: darwin

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  darwin-test:
    runs-on: macos-latest
    steps:
      - name: install
        run: |
          pwd
          make install
      - name: deploy
        run: make deploy
