name: darwin

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  darwin-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        working-directory: ./
        run: |
          make install
      - name: deploy
        run: |
          make deploy
