name: darwin

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - './ubuntu/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - './ubuntu/**'
  workflow_dispatch:
    paths-ignore:
      - 'README.md'
      - './ubuntu/**'

jobs:
  darwin-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        working-directory: ./
        run: |
          make install
      - name: deploy
        working-directory: ./
        run: |
          make deploy
