name: ubuntu

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - './darwin/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - './darwin/**'
  workflow_dispatch:
    paths-ignore:
      - 'README.md'
      - './darwin/**'

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        working-directory: ./
        run: |
          make install
      - name: deploy
        working-directory: ./
        run: |
          make deploy
      # - name: check .zshrc load
      #   working-directory: ~
      #   run: |
      #     zsh .zshrc 2> error.log; cat error.log
      #     if [ -s error.log ]; then false; fi
